"""One source of truth for the tech pack. Used by the PDF (v1 traditional) and the web viewer (v1 2.0).
Rule: a value is either read from a file, or it is TBC. Nothing guessed."""

STYLES = [
    {
        "key": "s01",
        "num": "01",
        "name": "Citibike Gumbit",
        "kind": "Graphic tee, front print, screen print",
        "line": "Gumbit on the GUMBIKE, riding out of a sky full of smoke. One drawing, black line, closed shapes.",
        "art": True,
        "art_file": "citibike gumbit 2.ai",
        "art_facts": [
            ("File", "citibike gumbit 2.ai, Illustrator, saved Sept 5, 2026"),
            ("Artboard", "9 x 12 in (648 x 864 pt)"),
            ("Paths", "All filled shapes. No live strokes."),
            ("Colors in file", "Black and white only. Document is RGB."),
            ("Edges", "Art runs off the artboard on all four sides"),
        ],
        "spec": [
            ("Style number", None),
            ("Blank", "Existing blank. Brand and style number TBC"),
            ("Body colors", None),
            ("Size run", None),
            ("Print method", "Screen print"),
            ("Ink type", "Plastisol, water based, or discharge: TBC"),
            ("Print", "Front only. Center front"),
            ("Print size", "TBC. Starting point: artboard at 100%, 9 x 12 in"),
            ("Down from collar", "TBC. Measured at center front from the collar seam"),
            ("Back print", "Signature only, center back neck"),
            ("Signature", "PJ's real signature file, never redrawn. Center back, below the collar. Size and drop TBC"),
            ("Ink color ref", "Pantone TCX or C for each ink: TBC"),
            ("Mesh count", "Per screen: TBC with the printer"),
            ("Screen sizes", "One print size for all sizes, or tiers by size range: TBC"),
            ("Tolerance", "Plus or minus, per measurement and per placement: TBC"),
            ("Neck label", "Printed or woven: TBC"),
            ("Hang tag", None),
            ("Packaging", None),
        ],
        "inks": [
            ("Ink 1", "Black line", "From file. Pantone or ink match TBC"),
            ("Ink 2", "White fills", "Open. Print white, or leave open so the shirt shows"),
            ("Underbase", "Only on dark shirts", "TBC with the printer"),
            ("Back ink", "Signature, back neck", "Same ink as the front line. TBC"),
        ],
        "decisions": [
            ("White fills", "The drawing has white filled shapes inside it: the clouds, the suit, the bike. On a white or cream shirt they disappear, so it prints as one ink. On any other color they either print white (a second ink) or go open and take the shirt color. Pick one before separations."),
            ("Hard edge", "The clouds and the road run off the artboard on all four sides. Printed as it is, the graphic reads as a hard 9 x 12 in rectangle. Keep the rectangle, or PJ closes the edges."),
            ("Line on dark shirts", "Black line disappears on a black shirt. A dark colorway needs a light line color, or this style stays on light shirts."),
            ("Signature size", "The signature sits center back just below the collar. Its width and how far down it sits are open. The viewer lets you try both; the numbers stay TBC until PJ signs off."),
            ("RGB to spot", "The file is RGB. Separations should convert the black to a spot ink before films."),
        ],
    },
    {
        "key": "s02",
        "num": "02",
        "name": "Next Style",
        "kind": "Graphic tee, TBA",
        "line": "Empty on purpose. Drop the art in and fill the same fields.",
        "art": False,
        "art_file": None,
        "art_facts": [
            ("File", None),
            ("Artboard", None),
            ("Paths", None),
            ("Colors in file", None),
            ("Edges", None),
        ],
        "spec": [
            ("Style number", None),
            ("Blank", None),
            ("Body colors", None),
            ("Size run", None),
            ("Print method", "Screen print"),
            ("Ink type", None),
            ("Print", None),
            ("Print size", None),
            ("Down from collar", None),
            ("Back print", None),
            ("Signature", None),
            ("Ink color ref", None),
            ("Mesh count", None),
            ("Screen sizes", None),
            ("Tolerance", None),
            ("Neck label", None),
            ("Hang tag", None),
            ("Packaging", None),
        ],
        "inks": [("Ink 1", None, None), ("Ink 2", None, None), ("Ink 3", None, None)],
        "decisions": [],
    },
]

PRINTER_RULES = [
    ("Vector only", "print from the .ai"),
    ("Strike-off first", "before the run"),
    ("PJ signs off", "every strike-off"),
    ("No redraws", "his line stays his line"),
    ("TBC means ask", "never fill a gap"),
    ("Match the flat", "placement as drawn"),
]

SIZE_POMS = ["Body length from HPS", "Chest, 1 in below armhole", "Sweep (hem width)", "Shoulder width",
             "Sleeve length from shoulder", "Sleeve opening", "Neck width, seam to seam", "Front neck drop", "Back neck drop"]
