"""One source of truth for the tech pack. Used by the PDF (v1 traditional) and the web viewer (v1 2.0).
Rule: a value is either read from a file, or it is TBC. Nothing guessed."""

STYLES = [
    {
        "key": "s01",
        "num": "01",
        "name": "Citibike Gumbit",
        "kind": "Graphic tee, front print, screen print",
        "line": "Gumbit on the GUMBIKE, riding out of a sky full of smoke. One drawing, black line, closed shapes.",
        "art": True,
        "art_file": "citibike gumbit 2.ai",
        "art_facts": [
            ("File", "citibike gumbit 2.ai, Illustrator, saved Sept 5, 2026"),
            ("Artboard", "9 x 12 in (648 x 864 pt)"),
            ("Paths", "All filled shapes. No live strokes."),
            ("Colors in file", "Black and white only. Document is RGB."),
            ("Edges", "Art runs off the artboard on all four sides"),
        ],
        "spec": [
            ("Style number", None),
            ("Blank", "Shaka Wear SHGD, Unisex Max Heavyweight Garment-Dyed Tee. 7.5 oz, 100% USA cotton, 16 singles, garment-dyed. Women's blank TBC"),
            ("Body colors", None),
            ("Size run", None),
            ("Print method", "Screen print"),
            ("Ink type", "Plastisol, water based, or discharge: TBC"),
            ("Print", "Front only. Center front"),
            ("Print size", "TBC. Starting point: artboard at 100%, 9 x 12 in"),
            ("Down from collar", "TBC. Measured at center front from the collar seam"),
            ("Back print", "Signature only, center back neck"),
            ("Signature", "PJ's real signature file, never redrawn. Center back, below the collar, in the colourway's accent colour. Size and drop TBC"),
            ("Ink color ref", "Pantone TCX or C for each ink: TBC"),
            ("Mesh count", "Per screen: TBC with the printer"),
            ("Screen sizes", "One print size for all sizes, or tiers by size range: TBC"),
            ("Tolerance", "Plus or minus, per measurement and per placement: TBC"),
            ("Neck label", "Printed or woven: TBC"),
            ("Hang tag", None),
            ("Packaging", None),
        ],
        "inks": [
            ("Ink 1", "Black line", "From file. Pantone or ink match TBC"),
            ("Ink 2", "White fills", "Open. Print white, or leave open so the shirt shows"),
            ("Underbase", "Only on dark shirts", "TBC with the printer"),
            ("Back ink", "Signature, back neck", "The colourway's accent colour (Classic: black, same as the line). Pantone TBC"),
        ],
        "decisions": [
            ("White fills", "The drawing has white filled shapes inside it: the clouds, the suit, the bike. On a white or cream shirt they disappear, so it prints as one ink. On any other color they either print white (a second ink) or go open and take the shirt color. Pick one before separations."),
            ("Hard edge", "The clouds and the road run off the artboard on all four sides. Printed as it is, the graphic reads as a hard 9 x 12 in rectangle. Keep the rectangle, or PJ closes the edges."),
            ("Line on dark shirts", "Black line disappears on a black shirt. A dark colorway needs a light line color, or this style stays on light shirts."),
            ("Signature size", "The signature sits center back just below the collar. Its width and how far down it sits are open. The viewer lets you try both; the numbers stay TBC until PJ signs off."),
            ("RGB to spot", "The file is RGB. Separations should convert the black to a spot ink before films."),
        ],
    },
    {
        "key": "s02",
        "num": "02",
        "name": "New York Layer Cake",
        "kind": "Graphic tee, front print, screen print",
        "line": "New York as a layer cake: the skyline on top, cut open to the subway, the rats and the gators underneath. One drawing, black line with grey tones.",
        "art": True,
        "art_file": "PATCH NEW YORK LAYER CAKE COLOR PJ OROURKE BW SCREEN PRINT.ai",
        "art_facts": [
            ("File", "PATCH NEW YORK LAYER CAKE COLOR PJ OROURKE BW SCREEN PRINT.ai, Illustrator 29, saved Sept 21, 2026"),
            ("Artboard", "70.6 x 82.8 in. The art itself is 62.0 x 70.0 in (ArtBox), not at print size"),
            ("Paths", None),
            ("Colors in file", "Black, white and grey tones (about 15% of the art is grey). No colour"),
            ("Edges", "Closed: the cake sits inside the artboard on a transparent background"),
        ],
        "spec": [
            ("Style number", None),
            ("Blank", "TBC. Starting point: Style 01's blank, Shaka Wear SHGD"),
            ("Body colors", None),
            ("Size run", None),
            ("Print method", "Screen print"),
            ("Ink type", "Plastisol, water based, or discharge: TBC"),
            ("Print", "Front only. Center front"),
            ("Print size", "TBC. Starting point: 12 in wide (about 12 x 13.6 in), scaled from the art"),
            ("Down from collar", "TBC. Measured at center front from the collar seam"),
            ("Back print", "Signature only, center back neck"),
            ("Signature", "PJ's real signature file, never redrawn. Center back, below the collar, in the colourway's accent colour. Size and drop TBC. The art also carries his signature, bottom right"),
            ("Ink color ref", "Pantone TCX or C for each ink: TBC"),
            ("Mesh count", "Per screen: TBC with the printer. Grey tones need a halftone decision first"),
            ("Screen sizes", "One print size for all sizes, or tiers by size range: TBC"),
            ("Tolerance", "Plus or minus, per measurement and per placement: TBC"),
            ("Neck label", "Printed or woven: TBC"),
            ("Hang tag", None),
            ("Packaging", None),
        ],
        "inks": [("Ink 1", "Black line", "From file. Pantone or ink match TBC"),
                 ("Ink 2", "White fills", "Open. Print white, or leave open so the shirt shows"),
                 ("Grey tones", "About 15% of the art", "Halftone, solid, or drop: TBC with the printer"),
                 ("Back ink", "Signature, back neck", "The colourway's accent colour (Classic: black, same as the line). Pantone TBC")],
        "decisions": [
            ("Grey tones", "About 15% of the drawing is grey (building faces, windows, the cake's sides). A one-colour screen print can't print grey: convert the greys to halftone dots, print them as solid line colour, or drop them. Pick before separations."),
            ("Print size", "The art is 62 x 70 in in the file, so it prints scaled down: 12 in wide is about 19% of the file. The smallest detail (subway riders, windows, the rats) gets very small. Check a strike-off at actual size before settling the width or screen tiers."),
            ("Two signatures", "PJ's signature is drawn into the art (bottom right, by the cake plate) and also prints at the back neck. Keep both, or drop one."),
            ("White fills", "The buildings and the cake are white-filled shapes. On a cream or white shirt they disappear; on a colour they print white (a second ink) or go open and take the shirt colour. Pick one before separations."),
            ("Patch or tee", "The file is named PATCH ... BW SCREEN PRINT. This pack treats it as a front tee print (Michael, 2026-09-28)."),
        ],
    },
    {
        "key": "s03",
        "num": "03",
        "name": "New York Fuckery",
        "kind": "Graphic tee, left chest + full back, one-colour screen print",
        "line": "The L train, a MetroCard and a 'no trains, take the L' sign, with NEW YORK FUCKERY in hand-drawn letters, knocked out of one solid circle. One ink; the shirt is the second colour.",
        "art": True,
        "art_file": "fuckery one color screen copy.pdf",
        "art_facts": [
            ("File", "fuckery one color screen copy.pdf, Illustrator 28.1 (Windows), saved Sept 21, 2026. A PDF, not the .ai"),
            ("Artboard", "11 x 17 in. Three circles of the same art, at print size: 10 1/8 in, 3 3/8 in and 2 3/4 in across"),
            ("Paths", None),
            ("Colors in file", "Black and white only, no colour. About 6% of the art is thin grey sketch lines inside the letters"),
            ("Edges", "Closed: each circle sits on a transparent background"),
        ],
        "spec": [
            ("Style number", None),
            ("Blank", "Shaka Wear SHGD, Unisex Max Heavyweight Garment-Dyed Tee. Women's blank TBC"),
            ("Body colors", None),
            ("Size run", None),
            ("Print method", "Screen print, one colour"),
            ("Ink type", "Plastisol, water based, or discharge: TBC"),
            ("Print", "Two placements: small over the left chest, large center back. Signature at the back neck"),
            ("Chest print", "TBC. Starting point: the 3 3/8 in circle from the file at 100%, centred 4 in to the wearer's left of center front"),
            ("Down from HPS", "TBC. Starting point: top of the chest circle 3 1/2 in below the high point of the shoulder"),
            ("Back print", "TBC. Starting point: the 10 1/8 in circle from the file at 100%, center back, top 4 in below the back collar"),
            ("Signature", "PJ's real signature file, never redrawn. Center back, below the collar, above the back circle. Colour and size TBC"),
            ("Ink color ref", "Pantone TCX or C for the one ink: TBC"),
            ("Mesh count", "Per screen: TBC with the printer"),
            ("Screen sizes", "Two screens, chest and back. One size for every shirt size, or tiers: TBC"),
            ("Tolerance", "Plus or minus, per measurement and per placement: TBC"),
            ("Neck label", "Printed or woven: TBC"),
            ("Hang tag", None),
            ("Packaging", None),
        ],
        "inks": [("Ink 1", "The circle, one colour", "Letters and drawing are knocked out, so the shirt shows through. Ink colour TBC; the viewer lets you try any"),
                 ("Underbase", "Only for a light ink on a dark shirt", "TBC with the printer"),
                 ("Back ink", "Signature, back neck", "Same ink as the circles (one colour on the whole tee), or the colourway's accent: TBC")],
        "decisions": [
            ("Chest size", "The file has two small circles, 3 3/8 in and 2 3/4 in. Use one for every size, or the small one for XS/S and women's."),
            ("Signature colour", "The circles are one ink. The signature in the same ink keeps the whole tee one colour; in the colourway accent it's a second ink on the back."),
            ("Grey sketch lines", "Thin grey pencil-style lines sit inside the white letters (about 6% of the art). One colour can't print grey: print them solid in the ink, halftone them, or drop them."),
            ("Vector file", "This is a PDF saved from Illustrator. Films should come from the .ai (Rules: print from the vector). Ask PJ for the .ai."),
            ("Placement", "Left chest and back are starting points from standard placements, not from PJ. Confirm the chest position and the back drop on a strike-off."),
        ],
    },
]

PRINTER_RULES = [
    ("Vector only", "print from the .ai"),
    ("Strike-off first", "before the run"),
    ("PJ signs off", "every strike-off"),
    ("No redraws", "his line stays his line"),
    ("TBC means ask", "never fill a gap"),
    ("Match the flat", "placement as drawn"),
]

SIZE_POMS = ["Body length from HPS", "Chest, 1 in below armhole", "Sweep (hem width)", "Shoulder width",
             "Sleeve length from shoulder", "Sleeve opening", "Neck width, seam to seam", "Front neck drop", "Back neck drop"]
